### PR TITLE
doc: Adds documents to DomainMatrix class

### PR DESCRIPTION
**Pull request by hyadav2k**
Reference to Task1 for #20987

Collaborative PR with @ks147 

#### Brief description of what is fixed or changed
Adds docs for DomainMatrix with the explanation of its methods and usage.

#### RELEASE NOTES

NO ENTRY

### CODE REVIEW

**Comment by hyadav2k** [comment]
@ks147, we both can work on this PR.
Ping @oscarbenjamin.

**Comment by ks147** [comment]
> @ks147, we both can work on this PR.
> Ping @oscarbenjamin.

Ping him where?

**Comment by ks147** [comment]
Also there are obviously a lot of merge conflicts. So we'll need to figure out what changes to keep from which branch

**Comment by ks147** [comment]
>https://github.com/sympy/sympy/pull/20991#issuecomment-787057500

According to this comment there is an rst file that needs to be added for the docs to actually show up on the Sympy Documentation page. I was thinking that I'll resolve the merge conflicts while you can get started on the rst file. I actually don't know how much work needs to be added to the rst file, If it's a fair amount then we can divide that too

**Comment by hyadav2k** [comment]
> Ping him where?

No, I'm just tagging, to notify about the new PR.

**Comment by hyadav2k** [comment]
@ks147, implementing a `rst` file for the `DomainMatrix` will take more than a fair amount of time, and I believe we collaborating on it will result to be more beneficent and efficient w.r.t time. 

I believe we should first resolve all the conflicts in this PR, and make it mergeable and then we will open a new PR for the `rst` file on which we both can work. The main reason to make a new PR for the `rst` file is that so that the basic docs can be added to master and if someone wants to get started with working on `DomainMatrix`, they will have something to look at, else if we will go for `rst` file in this PR, it will take time.

If you agree we can start by dividing the work in resolving conflicts and then review each other's work later.
Kindly share your opinion.
Thanks.

**Comment by ks147** [comment]
> @ks147, implementing a `rst` file for the `DomainMatrix` will take more than a fair amount of time, and I believe we collaborating on it will result to be more beneficent and efficient w.r.t time.
> 
> I believe we should first resolve all the conflicts in this PR, and make it mergeable and then we will open a new PR for the `rst` file on which we both can work. The main reason to make a new PR for the `rst` file is that so that the basic docs can be added to master and if someone wants to get started with working on `DomainMatrix`, they will have something to look at, else if we will go for `rst` file in this PR, it will take time.
> 
> If you agree we can start by dividing the work in resolving conflicts and then review each other's work later.
> Kindly share your opinion.
> Thanks.

@hyadav2k I am sorry I must have missed this comment. I think we should proceed exactly as you say. FIrst put up a PR for the main docs, so people can use DomainMatrix and then make a new PR for `rst` file

**Comment by hyadav2k** [comment]
N.P.

**Pull request closed without merging**
